### PR TITLE
Fix minimum price

### LINKED ISSUE #44: Review scenario when series price is less than campground minimum fee
What would happen if the `price` selected by the creator is less than the campground minimum fee?

https://github.com/campgroundco/nft-contract/blob/10d424d70077fece755af2a9f577e8c5b115f3aa/src/market.rs#L88-L95

If we are not validating this case, then I believe the token would become unbuyable. Does this make sense @andreespirela ?

### PR DESCRIPTION
**Pull request by acuarica**
Closes #44.

### CODE REVIEW

File: src/market.rs [hunk 1]
```diff
@@ -147,3 +138,18 @@ impl Contract {
...
+/// The second components represents the Campground fee.
+fn get_price_and_fee(trail_series: &TrailSeries) -> (u128, u128) {
+    if trail_series.price.0 > trail_series.campground_fee_near.0 {
+        (trail_series.price.0, trail_series.campground_fee_near.0)
+    } else {
+        (
+            trail_series.campground_fee_near.0,
+            trail_series.campground_fee_near.0,
+        )
+    }
```
Comment (acuarica) [inline src/market.rs:154]: @andreespirela @zo0r  when the price set by creator is less than `campground_fee_near`, the amount towards the creator becomes effectively `0`. This is because the `attached_deposit` in the buy method goes to Campground.

Is this the desired behaviour? Just to confirm we all are on the same page.

**Review by andreespirela — APPROVED** [review]
LGTM
